--- 
$:
  preprocess:
    '$.terraform.vars.access_key': 'eval'
    '$.terraform.vars.secret_key': 'eval'
    '$.terraform.vars.region': 'eval'
    '$.comment.providers.github.0.token': 'eval'

  emit:
    pattern:
      - /.+\.js.*$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i
  terraform:
    resource: '.resource'
    binary: './bin/terraform'
    use-cache: false
    vars:
      access_key: 'process.env.AWS_ACCESS_KEY_ID'
      secret_key: 'process.env.AWS_SECRET_ACCESS_KEY'
      region: 'process.env.AWS_DEFAULT_REGION'
  comment:
    providers:
      github:
        - token: 'process.env.GITHUB_ACCESS_TOKEN'
  e2e:
    pattern:
      - /.+\.e2e\.js$/i
    screenshot:
      enabled: false
      take-on-fail: true
      path: './tests/screenshots'
    browsers:
      - firefox

ec2:
  root: './root'
  terraform:
    apply: true
    destroy: true
    version: 0.11.0
    vars:
      region: 'eu-central-1'
